name: copy
description: copy file or copy direcotry

version: 1.0.0
homepage: https://www.sourcedev.cc
author: ydl <yang623601391@gmail.cn>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
